### ISSUE TITLE
Identify as a bot

### ISSUE THREAD

**Issue by atomjack** [alaingilbert/Turntable-API#266]
I recently learned that it is possible for the bot to identify itself as a bot to Turntable. All you have to do is send a websockets message of `api: 'user.set_bot'`. This is the result in the room list:

![screenshot_20210407_092122](https://user-images.githubusercontent.com/114672/113900444-abdf1a80-9782-11eb-910f-84695f3b9cd6.png)

I was able to modify the api code by adding this function and then running it after my bot (ChilloutMixerNinja) registered with the room:

```
  setAsBot(callback) {
    const rq = { api: 'user.set_bot' };
    return this._send(rq, callback);
  }
```

I could do a pull request but I wasn't sure if this should be built into Turntable-API by default, or should it just be up to the user of the API to run it in order to identify as a bot. @alaingilbert I'd appreciate your input!

**Comment by alaingilbert** [comment]
I would add the function, but I wouldn't call it automatically.

**Comment by atomjack** [comment]
Thanks @alaingilbert !
